### PR TITLE
#146622669 deploy to heroku

### PR DESCRIPTION
**Pull request by seyi-adeleke**
#### What does this PR do?
This PR adds the necessary changes for deployment
#### Description of Task to be completed?
Deploy to heroku.
#### How should this be manually tested?
[https://boromir-cfh-staging.herokuapp.com/](https://boromir-cfh-staging.herokuapp.com/)
#### Any background context you want to provide?
package lock is not not compatible with older versions of npm
#### What are the relevant pivotal tracker stories?
146622669
#### Screenshots (if appropriate)
screen shot 2017-06-13 at 5 03 57 pm

#### Questions:
none

### CODE REVIEW

**Comment by fokosun** [comment]
@seyi-adeleke this https://boromir-cfh-staging.herokuapp.com/ appears broken. You said we could manually test using this link.

**Comment by andela-Taiwo** [comment]
@seyi-adeleke  The app is crashing on heroku.
You need to look into that. I have attached a screenshot.
screen shot 2017-06-15 at 3 50 07 pm
.

**Comment by ajaps** [comment]
@seyi-adeleke, there seems to be  a problem with the application. i'm getting an 'Application Error',  when i use the link provided

**Comment by seyi-adeleke** [comment]
As discussed heroku is currently linked to auto deploy the staging branch which is currently breaking. My proposed changes fixes this issue. If you visit the link it should go through because heroku has been set to deploy #20. After merging I will then set it to autodeploy the staging branch instead.

**Comment by fokosun** [comment]
sounds good. @framky007 @metalmount approve

**Review by andela-Taiwo — APPROVED** [review]
Explanation sounds okay

**Review by ajaps — APPROVED** [review]
Good to go!

**Pull request merged**
